### ISSUE TITLE
SOCKETCLUSTER_WORKERS and SOCKETCLUSTER_BROKERS ?

### ISSUE THREAD

**Issue by renaudguerin** [SocketCluster/socketcluster#306] opened 2017-07-05 17:56 UTC
I'm sorry as Github issues are likely a wrong place to ask, but I'm not sure where else is appropriate for this project.

The Kubernetes broker and worker deployment definitions both have SOCKETCLUSTER_WORKERS and SOCKETCLUSTER_BROKERS as env variables.

I couldn't find them mentioned in the docs, I could track them down as integer values in the options dictionary of the SocketCluster object, but I couldn't find exactly when and how they end up being used.

Are they actually supposed to reflect the number of workers/brokers launched in the cluster ?

Does that mean that for example it's not possible to have Kubernetes autoscale the number of replicas, you also have to adjust these variables in both the broker and worker deployments every time any of them is scaled up/down, and restart all of the pods each time ?

Thanks !

**Comment by jondubois** [comment] 2017-07-05 18:22
@renaudguerin Good question, it deserves a long answer:

SC scales both vertically *and* horizontally. The vertical aspect (across multiple processes on a single host) is handled internally by SC itself and is static (since each host can only have a fixed number of CPU cores) - That is what `SOCKETCLUSTER_WORKERS` and `SOCKETCLUSTER_BROKERS` are about - Basically the number of processes of each type on each host. 

When discussing scaling in term of Kubenetes, this is for horizontal scaling; and there is no hard value there. You can just use the `kubectl scale --replicas=123 -f socketcluster-deployment.yaml` (or whatever) - This doesn't affect the number of worker/broker processes on each host, but it affects the number of instances that there are.

There are actually two kinds of message brokers in SC;
- `sc-broker` - Only brokering messages across processes within a single host.
- `scc-broker` - Which brokers messages across multiple hosts.

See this diagram for more info: https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md#how-it-works

There are performance benefits for having two levels of brokers like this; particularly as modern CPUs are getting more and more cores - It reduces the total number of messages that need to move between different hosts.

If your cluster is made up hosts that have a single CPU core, then I would advise to leave both `SOCKETCLUSTER_WORKERS` and `SOCKETCLUSTER_BROKERS` as `1`.

If each host has 4-core CPUs, then you can play safe and set both `SOCKETCLUSTER_WORKERS` and `SOCKETCLUSTER_BROKERS` to `4`.

That said, it's often better if the sum of `SOCKETCLUSTER_WORKERS` and `SOCKETCLUSTER_BROKERS` adds up to the number of cores on each host, so in many cases, you might find that `SOCKETCLUSTER_WORKERS = 3` and `SOCKETCLUSTER_BROKERS = 1` actually performs better (then the workers/brokers don't need to share CPU cores) but then in some cases you might find that your broker is actually too busy...

As you can guess, it's better if all the hosts in your cluster have the same number of CPU cores.

**Comment by renaudguerin** [comment] 2017-07-06 13:41
Thank you for this great answer. It could probably go straight into the docs !

Even with multi-core hosts, there are usually quite a few other processes running in a k8s cluster anyway, so I think it makes sense to just to leave these variables at 1, and just scale the number of replicas if needed (at worst several of them will end up on the same host).

Also, when you say "number of processes per host", in the Docker/k8s context this translates to "per pod" right ? You're forking n processes from a master process (much like a web server would do), all inside the same container correct ?

**Comment by jondubois** [comment] 2017-07-06 15:24
@renaudguerin Yes 'per pod' is more accurate than 'per host'.

In SCC's case though, because K8s automatically avoids port conflicts (and all SCC instances bind to the same port by default), it should never schedule more than one SC instance per host.

Yep, an SC instance runs multiple processes (workers and local brokers) within a single container.

I know that there have been debates about whether or not it's better to run single process per container when using Docker/K8s, but in this case, it would add a lot of complexity (especially around load balancing) and it would be less efficient.

I would be happy to revisit the current architecture at some point in the future if it turns out that there are benefits to having one process per container. It would be a lot of work but at least it should be possible to do without affecting the API.

**Comment by toredash** [comment] 2017-09-05 20:01
@jondubois I'm having a hard time understanding how SCC will scale, and how resources are used within SCC in K8s. I hope you have a few moments to spare to look at 

We are currently using SCC on AWS with OpenShift 3.6/Kubernetes 1.6. 

The deployment socketcluster is setup with SOCKETCLUSTER_WORKERS and SOCKETCLUSTER_BROKERS set to 1. scc-state and scc-broker is plain, using the deployment files listed in https://github.com/SocketCluster/socketcluster/tree/master/kubernetes

During testing, we have 20.000 clients subscribed to one channel and are publishing 1 event per second. We use 12x m4.large (2x vCPU / 8GB RAM) for compute nodes in k8s. socketcluster is not configured with SSL, SSL is terminated in a AWS ELB.

During the test, we see next to -nothing- in terms of CPU load, memory usage and network util. on the scc-broker pods. Is this expected behaviour ?

Above you write:
> In SCC's case though, because K8s automatically avoids port conflicts (and all SCC instances bind to the same port by default), it should never schedule more than one SC instance per host.

and

>I know that there have been debates about whether or not it's better to run single process per container when using Docker/K8s, but in this case, it would add a lot of complexity (especially around load balancing) and it would be less efficient.

I don't believe it is true that K8s won't schedule multiple instance., but I might be misunderstand you ? I'm able to schedule multiple socketcluster pods within the same compute node, nothing is limiting me from doing that unless you use podAntiAffinity on the deployment. I'm currently limiting each socketcluster pod to one core in k8s, and scale by adding multiple pods to the cluster to handle increase in load. Is this not the preferred way of doing it ?

If I'm reading you correctly, the best way to scale the socketcluster deployment is to use ENV variables (..._WORKERS and ..._BROKERS) to match your compute node core count(?). If yes, one should add podAntiAffinity rule so that only one socketcluster pod is running on each compute node.

Some input regarding this would be very helpful.

Also, if we subscribe to many clients at once(500 per second), the health-check in the socketcluster deployment starts to fail on every pod, causing the whole service to fail. I haven't figured out why, if was terminated on each socketcluster pod I could get it, but SSL is terminated at AWS. Any experience or advice around this ?

**Comment by jondubois** [comment] 2017-09-05 22:27
> I don't believe it is true that K8s won't schedule multiple instance., but I might be misunderstand you ? I'm able to schedule multiple socketcluster pods within the same compute node, nothing is limiting me from doing that unless you use podAntiAffinity on the deployment.

Note that you can have pods from different services sharing the same host in case that's what you were thinking. Based on the tests I did, K8s never assigned more than one pod of the same service to the same host because, for example there is only one port 8000 available on each host and the socketcluster service/deployment specifically reserves port 8000 - See https://github.com/SocketCluster/socketcluster/blob/master/kubernetes/socketcluster-service.yaml#L9 and https://github.com/SocketCluster/socketcluster/blob/master/kubernetes/socketcluster-deployment.yaml#L16

From what I understood, this is because K8s has some implicit affinity rules which prevents Pods which are assigned to the same port from running on the same host. I haven't checked with the latest versions of K8s though so I may be wrong (I know that they've done a fair bit of work around pod affinity and anti-affinity recently).

Maybe there are new approaches I'm not familiar with... If so, feel free to investigate and share. Maybe some of the SC .yaml files need to be updated for newer versions of K8s?

Using ENV variables is the recommended approach to scale up across CPU cores. Let me know if you can confirm for sure that podAntiAffinity rules are required now because I'm pretty sure that was a requirement before (can't remember the exact K8s version I tested with).

> Also, if we subscribe to many clients at once(500 per second), the health-check in the socketcluster deployment starts to fail on every pod, causing the whole service to fail. I haven't figured out why, if was terminated on each socketcluster pod I could get it, but SSL is terminated at AWS. Any experience or advice around this ?

How does CPU usage look on the socketcluster pods? If SC is overloaded (and becomes slow/unresponsive) then it can cause the health check to fail. You may want to do some rate-limiting in SC or in your load balancer.

I have not experienced this - Feel free to let me know if you find the problem/solution. The health check is done by K8s using a route which is exposed by SC. See this https://github.com/SocketCluster/socketcluster/blob/master/sample/worker.js#L25  - The module attaches a HTTP/S route to the express app https://github.com/SocketCluster/sc-framework-health-check/blob/master/index.js#L9

**Comment by toredash** [comment] 2017-09-06 18:34
K8s will try to spread out pods from the same deployment to multiple hosts if possible, but there is nothing limiting it to have many of the same pod on the same host.

> Using ENV variables is the recommended approach to scale up across CPU cores. Let me know if you can confirm for sure that podAntiAffinity rules are required now because I'm pretty sure that this was not a requirement before (can't remember the exact K8s version I tested with).

If the goal is to run one socketcluster pod on each compute node, and use all available cores on that particular compute node, then you indeed node podAntiAffinity rules setup

Example from our environment, we run 6 replicas of socketcluster, and we have 6 compute nodes:
`$ oc get pod -l app=socketcluster  | grep socket | awk '{print $1}' | xargs -n 1 oc describe pod | grep Node: | sort | uniq -c
   2 Node:			ip-10-20-4-109.eu-central-1.compute.internal/10.20.4.109
   1 Node:			ip-10-20-4-158.eu-central-1.compute.internal/10.20.4.158
   1 Node:			ip-10-20-5-124.eu-central-1.compute.internal/10.20.5.124
   1 Node:			ip-10-20-5-97.eu-central-1.compute.internal/10.20.5.97
   1 Node:			ip-10-20-6-180.eu-central-1.compute.internal/10.20.6.180`

Here, two pods are sharing the same host, this isn't a issue regarding port assignment, since each pod has its own IP.

You can verify this by using a simple nginx container:
`$ oc run nginx --image nginx --replicas=20

$oc get pod   | grep nginx | awk '{print $1}' | xargs -n 1 oc describe pod | grep Node: | sort | uniq -c
   4 Node:			ip-10-20-4-109.eu-central-1.compute.internal/10.20.4.109
   3 Node:			ip-10-20-4-158.eu-central-1.compute.internal/10.20.4.158
   5 Node:			ip-10-20-5-124.eu-central-1.compute.internal/10.20.5.124
   2 Node:			ip-10-20-5-97.eu-central-1.compute.internal/10.20.5.97
   1 Node:			ip-10-20-6-175.eu-central-1.compute.internal/10.20.6.175
   5 Node:			ip-10-20-6-180.eu-central-1.compute.internal/10.20.6.180

$ oc get pod   | grep console | awk '{print $1}' | xargs -n 1 oc describe pod | grep IP:
IP:			172.16.16.96
IP:			172.16.20.118
IP:			172.16.22.83
IP:			172.16.16.95
IP:			172.16.16.99
IP:			172.16.10.118
IP:			172.16.10.120
IP:			172.16.14.70
IP:			172.16.16.98
IP:			172.16.16.97
IP:			172.16.22.84
IP:			172.16.18.74
IP:			172.16.20.119
IP:			172.16.10.117
IP:			172.16.22.80
IP:			172.16.22.81
IP:			172.16.14.71
IP:			172.16.14.69
IP:			172.16.22.82
IP:			172.16.10.119`

There seems to be some parts that is not to clear when it comes to using K8s with SCC. You have given me valuable input and I will share what I can once we have done all of our testing and optimisation. Thanks for the quick reply

**Comment by jondubois** [comment] 2017-09-06 19:00
@toredash Thanks for the info. Is it possible to set this no-host-sharing anti-affinity rule in a generic way inside `socketcluster-deployment.yaml` https://github.com/SocketCluster/socketcluster/blob/master/kubernetes/socketcluster-deployment.yaml?

It would be a good default to have.

**Comment by toredash** [comment] 2017-09-27 12:30
@jondubois I've made a PR (https://github.com/SocketCluster/socketcluster/pull/331) to add podAntiAffinity rules to socketcluster deployment.

An alternative approach, that seems to be betterfor my usecase, is using DaemonSet (https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) - this way I always ensure that I have one socketcluster instance running on every k8s nodes available. You can also select nodes based on labels.

When I add or remove k8s nodes in my cluster, new socketcluster instances is brought up/down with the cluster resize, always using all available cores since that is what I've configured the DaemonSet to do.
---
Also, regarding my last reply: The reason why the current deployment file for socketcluster doesn't work as intended, is also related to resource assignment (or lack thereof) to the deployment specification (https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/). 

When no limit or request is made, k8s doesn't know what the particular pod may require in terms of resources. For all it knows, it may be 1 full core, og just 1/100th of a core. Hence, it can and will schedule multiple instances on the same k8s node.

Using podAntiAffinity, you at least ensure only one particular type of pod is running on one k8s node at any given time.

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Closed** 2018-04-09 00:16 UTC
