### ISSUE TITLE
EXCEPTION: SocketProtocolError: Socket hung up

### ISSUE THREAD

**Issue by ansarizafar** [SocketCluster/socketcluster#184] opened 2016-05-25 09:49 UTC
Socketcluster client is working fine in chrome for desktop but getting this error in firefox for desktop and Chrome for android.

**Comment by jondubois** [comment] 2016-05-25 10:13
@ansarizafar It works fine in Firefox for me. Which version are you using for the client and the server?

**Comment by ansarizafar** [comment] 2016-05-25 11:12
@jondubois I am using "socketcluster": "^4.6.1" and  "socketcluster-client": "^4.3.17". Client also doesn't work with  ionic2 app.

**Comment by jondubois** [comment] 2016-05-25 11:24
@ansarizafar What options are you using on the server (SocketCluster constructor) and client?

**Comment by ansarizafar** [comment] 2016-05-25 12:33
Here is my server code 
```
import {SocketCluster} from 'socketcluster';
import os from 'os';
import path from 'path';

const numCpus = os.cpus().length;


export const options = {
  authKey: process.env.JWT_SECRET || '2r65sMNTWnNmDb1TzBrHAtT4n7RlBw2srPVKDOPo33Oo/TYZZAAThYj/n3rnWsLRXw3mNbmOGhnCuVWO+94BVA==',
  logLevel: 1,
  // change this to scale vertically
  workers: 1 || numCpus,
  brokers: 1,
  port: process.env.PORT || 3000,
  appName: 'Restock',
  wsEngine: 'uws',
  allowClientPublish: false,
  initController: path.join(__dirname, '/init.js'),
  workerController: path.join(__dirname, '/worker.js'),
  brokerController: path.join(__dirname, '/broker.js'),
  socketChannelLimit: 1000,
  crashWorkerOnError: true,
  rebootWorkerOnCrash: true
  
};
new SocketCluster(options);
```
Client code 
```
const options = {
    //protocol: 'https',
    hostname: 'server-hlynjegodp.now.sh',
    port: 80,
     rejectUnauthorized: false 
    //hostname: 'localhost',
   // port: 3000
};
    (<any>window).Server = SocketCluster.connect(options); 
```

**Comment by jondubois** [comment] 2016-05-25 12:52
@ansarizafar It's difficult to say but these types of issues are usually caused by a mismatch between the client and server settings. Maybe the port numbers don't match, or maybe the hostname is incorrect...

The best way to check is to use the simplest settings possible, check that it works and then gradually add more options.

**Comment by ansarizafar** [comment] 2016-05-25 13:36
If its a settings issue then why its working in Chrome for desktop. You can check this link [http://restock.surge.sh/](http://restock.surge.sh/)

**Comment by jondubois** [comment] 2016-05-25 13:49
When I visit that link using Chrome, I'm also getting SocketProtocolError: Socket hung up (same as Firefox).

**Comment by ansarizafar** [comment] 2016-05-25 13:56
I am using Google Chrome Version 50.0.2661.75 (64-bit) on a Ubuntu machine. Its working without any problem.

**Comment by jondubois** [comment] 2016-05-25 13:56
I'm on Ubuntu with Chrome 48.0.2564.109

**Comment by jondubois** [comment] 2016-05-25 13:57
I'm getting
```
WebSocket connection to 'ws://server-hlynjegodp.now.sh/socketcluster/' failed: Error during WebSocket handshake: Unexpected response code: 301

EXCEPTION: SocketProtocolError: Socket hung up
```

**Comment by ansarizafar** [comment] 2016-05-25 13:58
Strange, If you want I can share my screen and show you the console log.

**Comment by jondubois** [comment] 2016-05-25 13:59
Maybe we can chat here instead: https://gitter.im/SocketCluster/socketcluster

**Comment by jondubois** [comment] 2016-05-25 14:03
WHen I look at the ws:// request (in Chrome still), it says 301 Moved Permanently

**Comment by ansarizafar** [comment] 2016-05-25 14:05
Check this screenshot 
![image](https://cloud.githubusercontent.com/assets/5788284/15542769/90161872-22ab-11e6-84b8-87ee8b441630.png)

**Comment by jondubois** [comment] 2016-05-25 14:10
![screenshot from 2016-05-26 00-07-56](https://cloud.githubusercontent.com/assets/1187447/15542934/2d19605a-22d6-11e6-85d6-a54c39790be8.png)

**Comment by jondubois** [comment] 2016-05-25 14:11
Something is sending back a `301 moved permanently response code`

**Comment by ansarizafar** [comment] 2016-05-25 14:13
I am getting the same response in Firefox and facing the same issue even if I run the server and client locally.

**Comment by jondubois** [comment] 2016-05-25 14:15
Is it possible to invoke a global socketCluster.connect from the console somehow (for me to test)?

**Comment by ansarizafar** [comment] 2016-05-25 14:18
Global socketcluster client is available on window.Server

**Comment by jondubois** [comment] 2016-05-25 14:18
This is very unlikely (though I'll admit, not impossible) to be a problem with SC itself - Otherwise others would have noticed the issue too. Plenty of people/companies are using SC with various frameworks including ionic and React native in production right now so there must be something else happening.

**Comment by jondubois** [comment] 2016-05-25 14:20
Are you running this behind a proxy/load balancer?

**Comment by jondubois** [comment] 2016-05-25 14:21
I keep getting status code `301` which is not something the SC server would ever send back.

**Comment by jondubois** [comment] 2016-05-25 14:24
Maybe try reinstalling socketcluster client and server from scratch. Inside your project directory:
`npm remove socketcluster && npm remove socketcluster-client`

then

`npm cache clean`

then

`npm install socketcluster && npm install socketcluster-client`

**Comment by ansarizafar** [comment] 2016-05-25 14:27
I can understand. I am trying to find a solution from last few days. I want to use socketcluster with a web and ionic2 app. I am using [https://t.co/UdG6eZSUxA](https://t.co/UdG6eZSUxA) for Server hosting and surge.sh for client hosting. I am facing the same problem If I run both server and client on my local machine. I have already removed and reinstalled both server and client packages.

**Comment by jondubois** [comment] 2016-05-25 14:31
What's your Node.js version?

**Comment by ansarizafar** [comment] 2016-05-25 14:32
I am using Node ver 5.7.0 and npm ver 3.6.0

**Comment by jondubois** [comment] 2016-05-25 14:37
Try to setup a completely new project from scratch:
`sudo npm remove -g socketcluster`
then
`sudo npm cache clean`
then
`sudo npm install -g socketcluster`
then
`socketcluster create newproject`
then `cd` inside newproject
then `node server`

then visit in browser `http://localhost:8000`

If that doesn't work then there must be something strange happening - Maybe you have a Firewall on your machine which is blocking WebSocket connections?

**Comment by ansarizafar** [comment] 2016-05-25 14:40
As I said, I am facing same issue on local machine. If firewall is blocking then why its working with Chrome ver 50

**Comment by jondubois** [comment] 2016-05-25 14:59
It works for me in every browser locally and remote and it seems to also work for the hundreds of developers who downloaded and used SC today.

I believe 100% that it's not working for you.
But I suspect that there is something unusual about your machine which is causing the problem. Sorry I cannot be much help there. Your best chance is to try a fresh setup from scratch - And try getting THAT to work locally before trying anything else.

**Comment by tomasvts** [comment] 2016-05-25 16:10
I would take a look at your nginx config, maybe you are making a redirect 301 there

**Comment by sandyplace** [comment] 2016-05-30 21:04
FYI: using uws appears to cause this same message using the latest Microsoft Edge browser as well.

**Comment by jondubois** [comment] 2016-05-31 01:46
@sandyplace Does it work in Firefox for you?

**Comment by ansarizafar** [comment] 2016-05-31 05:06
@tomasvts I was not able to find a solution and I am  not using socketcluster for my project now.

**Comment by sandyplace** [comment] 2016-05-31 05:14
@jondubois Works fine with Firefox and chrome. No worries, will use ws as the engine for now.

**Comment by efkan** [comment] 2016-07-14 16:51
I get the same message as a **warning** after the client disconnection at every time.


```
client connected
client disconnected
1468514606780 - Origin: Worker (PID 4268)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (D:\Work Space\Projects\a_web\node_modules\socketcluster-server\scsocket.js:193:17)
    at WebSocket.<anonymous> (D:\Work Space\Projects\a_web\node_modules\socketcluster-server\scsocket.js:70:10)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (D:\Work Space\Projects\a_web\node_modules\ws\lib\WebSocket.js:927:10)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickDomainCallback (node.js:410:17)
```

**Comment by jondubois** [comment] 2016-07-14 18:22
@efkan What kind of clients are you using? Are you using the JavaScript `socketcluster-client`? What is your version of `socketcluster`?

**Comment by efkan** [comment] 2016-07-14 18:51
I try to use an Android app which is developed in `react-native`.
Yes, I am using JavaScript `socketcluster-client` (**not** client for Android) to connect to the server.

Versions of the `server` libraries:
`socketcluster: ^4.6.2`
`socketcluster-client: ^4.3.19`

The version of the `client` library:
`socketcluster-client: ^4.3.19`

Node.js server runs on Windows. And `wsEngine` option has been set as `ws`.

Thank you..

ps: The issue is not urgent for me now. I've just let you know.

**Comment by jondubois** [comment] 2016-07-14 20:51
@efkan This error means that the  client socket is disconnecting incorrectly - Without sending a close control frame. Is there something in your code which could be blocking a close message? E.g. Are you using middleware? SC should send a `'#disconnect'` event before it disconnects itself.

**Comment by efkan** [comment] 2016-07-15 06:49
After reading your explanation, the warning message sounds normal to me.

An app is an `activity` in Android. And the activities have some methods that run in different cases. For now, react-native handles only `onPause`, `onResume` and `onDestroy` case methods.

So an app created for running on Android, turns to `onPause` mode when the user opens another app or presses the `home` button to go to the main screen on the phone. In this case socket connection is _still alive_. That's good.

However if an app is closed by the user intentionally that means app has been destroyed. Like hard resetting the computer. I get the warning message when destroying the app. Then the SC client cannot send a `#disconnect` event at all.

I'd like to know what happens if the SC client doesn't send a `#disconnect` event at all ?
(`scServer.clients` appearances is OK when the destroying the App)

And also I wonder that, can I handle `Socket hang up` warning/error to shut up that :) I can already handle that error message in `socket.on('error')` event. Emerging that warning seems not necessary. Is it ?

Thanks for your helps and `SocketCluster`.

**Comment by jondubois** [comment] 2016-07-15 07:22
@efkan The ` SocketProtocolError: Socket hung up` warning shouldn't cause problems and is generally safe to ignore.

You can change the `logLevel` option on the server to `1` and that should hide 'warnings'.
Or you could even set the logLevel to `0` and log all the errors and warnings yourself (so you can be more selective about which ones to show).

**Comment by efkan** [comment] 2016-07-15 07:45
It works. A useful option. Knowing that there is no an important issue is good.

Thanks..

**Closed** 2016-08-04 18:56 UTC

**Comment by aamirmsw** [comment] 2016-08-24 11:13
Hey all I,m using socket cluster and getting this error "Firefox can’t establish a connection to the server at ws://......

**Comment by jondubois** [comment] 2016-08-24 14:12
@aamirmsw check:

- That the client is pointing to the correct host and port
- That you are using matching security level on the client and server I.e. `ws://` vs `wss://`

Can you paste you `socketCluster.connect(options)` call here?

**Comment by aamirmsw** [comment] 2016-08-24 14:23
var options = {
    port: 8000
  };
  var socket = socketCluster.connect(options);
  socket.on('connect', function () {
    console.log('CONNECTED');
  }); 
Is it correct ?I have put it in .html file including socketcluster.js file.

**Comment by jondubois** [comment] 2016-08-24 19:50
@aamirmsw Is your server running on port 8000?
What version of Node.js and socketcluster and socketcluster-client are you using?

**Comment by aamirmsw** [comment] 2016-08-25 06:44
Yes it is runing on port 8000, Now my problem has been solved its working fine ,Thak you !

**Comment by 493326889** [comment] 2016-11-16 06:59
can i use socketcluster-client in node?
i have run a server and listening port 8000
`{
	workers: cpuNums, // Number of worker processes
	brokers: 1, // Number of broker processes
	port: 8000, // The port number on which your server should listen
	appName: 'myapp', // A unique name for your app

	// Switch wsEngine to 'uws' for a MAJOR performance boost (beta)
	wsEngine: 'uws',

	/* A JS file which you can use to configure each of your
	 * workers/servers - This is where most of your backend code should go
	 */
	workerController: __dirname + '/worker.js',

	/* JS file which you can use to configure each of your
	 * brokers - Useful for scaling horizontally across multiple machines (optional)
	 */
	brokerController: __dirname + '/broker.js',

	// Whether or not to reboot the worker in case it crashes (defaults to true)
	rebootWorkerOnCrash: true
}`

and use socketcluster-client in node, then run it ,but it occured error.

`var socketCluster = require('socketcluster-client');

var options = {
	host: "127.0.0.1",
	port: "8000"
};

var socket = socketCluster.connect(options);
socket.on('connect', function() {
	console.log('CONNECTED');
});
`
error msg:
SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (D:\dev\websocket\websocket-server-test\test\
node_modules\socketcluster-client\lib\scsocket.js:596:15)
    at Emitter.<anonymous> (D:\dev\websocket\websocket-server-test\test\node_mod
ules\socketcluster-client\lib\scsocket.js:285:12)
    at Emitter.emit (D:\dev\websocket\websocket-server-test\test\node_modules\co
mponent-emitter\index.js:131:20)
    at Emitter.SCEmitter.emit (D:\dev\websocket\websocket-server-test\test\node_
modules\sc-emitter\index.js:28:26)
    at Emitter.SCTransport._onClose (D:\dev\websocket\websocket-server-test\test
\node_modules\socketcluster-client\lib\sctransport.js:168:30)
    at WebSocket.wsSocket.onerror (D:\dev\websocket\websocket-server-test\test\n
ode_modules\socketcluster-client\lib\sctransport.js:97:12)
    at WebSocket.onError (D:\dev\websocket\websocket-server-test\test\node_modul
es\socketcluster-client\node_modules\ws\lib\WebSocket.js:452:14)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at ClientRequest.onerror (D:\dev\websocket\websocket-server-test\test\node_m
odules\socketcluster-client\node_modules\ws\lib\WebSocket.js:711:10)

**Comment by jondubois** [comment] 2016-11-16 08:54
The client options to connect should be `hostname: '127.0.0.1'` instead of `host: '127.0.0.1'`.

**Comment by jondubois** [comment] 2016-11-16 09:00
@493326889 ^

**Comment by 493326889** [comment] 2016-11-16 09:03
@jondubois  thanks !!!!

**Comment by 493326889** [comment] 2016-11-16 09:17
@jondubois  
i also have another question;
`var socketCluster = require('socketcluster-client');


// var useTimesArray = [];
// var report = require('./report'),
// 	cupNum = require('os').cpus().length;

var CONNECT_MAX = 1000,
	socketArr = [];


var options = {
	hostname: "127.0.0.1",
	port: "22282"
};

var i = 0;
while (i < CONNECT_MAX) {
	i++;
	socketArr.push(socketCluster.connect(options));

	socketArr[i - 1].on('connect', function() {
		console.log('CONNECTED ' + i);
	});

	socketArr[i - 1].on('rand', function(data) {
		console.log('RANDOM STREAM: ' + data.rand);
	})

}`

when i make 1000 connect to the server, but the server log  current count is 1。
`var count = 0;

    scServer.on('connection', function(socket) {
        count++;
        console.log('current connection: ' + count);
       
        var interval = setInterval(function() {
            socket.emit('rand', {
                rand: Math.floor(Math.random() * 5) + 'num:' + count + 'pid:' + process.pid
            });
        }, 1000);

        socket.on('disconnect', function() {
            clearInterval(interval);
        });
    });`

**Comment by jondubois** [comment] 2016-11-16 10:22
@493326889 That's because SC will reuse connections by default. To turn this off, you can set the `multiplex` option to false here: http://socketcluster.io/#!/docs/api-socketcluster-client

**Comment by lokielse** [comment] 2018-03-06 13:23
- Working with Chrome.
- Firefox(maxOS 58.0.2) not working	
- OS: macOS High Serria 10.13.3 (17D102)


Firefox console error

    uncaught exception: SocketProtocolError: Socket hung up

<img width="733" alt="default" src="https://user-images.githubusercontent.com/1573211/37034329-efd6ed30-2183-11e8-8eed-ec6ff5fb20f0.png">

<img width="731" alt="default" src="https://user-images.githubusercontent.com/1573211/37034480-60cacfe8-2184-11e8-897a-fa5f1107cfc6.png">


```js
var options = {
    hostname: 'localhost',
    port: 8000
}
var socket = socketCluster.connect(options)
```
