### ISSUE TITLE
Socket fails to transfer large objects

### ISSUE THREAD

**Issue by hyatt03** [SocketCluster/socketcluster#149] opened 2016-01-14 12:42 UTC
Hello

I am experiencing a weird bug during transfer of large javascript objects (See [this gist](https://gist.github.com/hyatt03/514948b6c9b4dd343f2d) ).

The data never gets sent to the client, and I'm getting the following:
Client: 
```
Uncaught SocketProtocolError: Server ping timed out
```
Server: 
```
1452775307247 - Origin: Worker (PID 6991)
   [Warning] SocketProtocolError: Client pong timed out
    at Emitter.SCSocket._onSCClose (/Users/jonashyatt/Code/mobilsoeg/node_modules/socketcluster-server/scsocket.js:169:17)
    at [object Object].<anonymous> (/Users/jonashyatt/Code/mobilsoeg/node_modules/socketcluster-server/scsocket.js:140:10)
    at Timer.listOnTimeout (timers.js:92:15) 
```

Thanks

**Comment by happilymarrieddad** [comment] 2016-01-15 07:06
How large is the object so we can test it? Btw, you can chunk the data or you can increase the timeout.

**Comment by hyatt03** [comment] 2016-01-15 07:12
The object is in the gist

**Comment by simplesmiler** [comment] 2016-01-15 07:20
@hyatt03 do you publish (to all clients) or emit (to a single client) this data?

**Comment by hyatt03** [comment] 2016-01-15 07:22
Emit to a single client

**Comment by jondubois** [comment] 2016-01-15 07:55
@hyatt03 This object isn't very large. SC should be able to handle JSON objects with multiple hundreds of thousands of properties.

I tested with that exact object using the latest version of SC (and client) and the object arrived on the client almost instantly. Are you sure that you're not accidentally sending more than this?

The error you mentioned might in fact happen if an object is too large - Or it could be caused by your client/browser being frozen.

Which version of SC are you using (client and server).
The server version shows up when you launch SC and to get the client version, you can just run ```socketCluster.version``` the browser console.

**Comment by hyatt03** [comment] 2016-01-15 07:57
^4.0.1 is specified in my package.json

**Comment by simplesmiler** [comment] 2016-01-15 07:59
From my experience, sc can transfer at least 300kb (b64 encoded image) in one batch without any issues.

**Comment by jondubois** [comment] 2016-01-15 08:02
Maybe can you update the submodule ```node_modules/socketcluster/node_modules/socketcluster-server``` to  ```v4.1.4``` and the client in ```node_modules/socketcluster-client``` to ```4.1.3``` - Just to be sure? These versions are a bit more stable.

**Comment by jondubois** [comment] 2016-01-15 08:04
Are you doing synchronous IO operations on the server (like reading a file synchornously)>

**Comment by hyatt03** [comment] 2016-01-15 09:02
The data isn't sent until it's ready (ie. no blocking file operations). I'll try to update now

**Comment by hyatt03** [comment] 2016-01-15 09:18
@jondubois  Same problem...

**Comment by jondubois** [comment] 2016-01-15 10:05
If you keep removing some properties from the object, does it work eventually?

**Comment by hyatt03** [comment] 2016-01-15 10:06
It works with smaller, similar objects

**Comment by jondubois** [comment] 2016-01-15 10:07
The exact object you provided works fine for me on Ubuntu. What OS are you using?

**Comment by hyatt03** [comment] 2016-01-15 10:09
OS X

**Comment by hyatt03** [comment] 2016-01-15 10:10
el capitan, it fails on both chrome, and safari in the ios sim

**Comment by jondubois** [comment] 2016-01-15 10:14
The way I'm doing it is I put your JSON object in a separate bigdata.js file then I have this code on the server:

```js
var bigData = require('./bigdata');
socket.on('getBigData', function () {
  socket.emit('bigData', bigData);
});
```

Then from the client I listen to the 'bigData' event using ```socket.on('bigData', function (data) {console.log('BIG DATA:', data);})``` then when I do ```socket.emit('getBigData')``` , I can see the whole object in the console.

**Comment by jfsimon** [comment] 2016-02-03 10:13
I have same kind problem. I use `socketcluster-server 4.1.4` and `socketserver-client 4.1.3`, and transferred data reach more than 2Mo. Data is emitted to only one client. It works well on my personal laptop (macbook + chrome or safari), but sometimes on my customer's one (windows + chrome), it leads to one of these errors:

**Case 1**

* Socket is disconnected
* `SocketProtocolError: Server ping timed out`, code: 4000
* Socket is re-connected

**Case 2**

* Socket is disconnected
* `SocketProtocolError: Socket hung up`, code: 1006. 
* Socket is re-connected

**In both cases**

* Then every minute (as configured with `pingInterval` option):
    * On client side: `SocketProtocolError: Server ping timed out`, then socket is disconnected
    * On server side: `SocketProtocolError: Client pong timed out` as a warning from a worker

**Notice that**

* The error seems to happen randomly (even sometimes with small objects).
* Sometimes this error happens as nothing happens in the browser.
* This **never** happens on personal my laptop (macbook + chrome or safari), only on my customer one.
* This also happens on my coworker laptop (windows + chrome).
* I made tests with Norton deactivated, same problem.

I'm sorry to bother you with this problem, but I really don't know how to fix it.

**Comment by jondubois** [comment] 2016-02-03 10:43
@jfsimon Make sure that your ```pingTimeout``` is more than 2 times as big as your ```pingInterval```.
So if your pingInterval is 1 minute, your pingTimeout should be like 2.5 minutes or higher.

**Comment by jfsimon** [comment] 2016-02-03 11:10
@jondubois thank you for your tip. I changed configuration from `pingInterval: 6000, pingTimeout: 7000` to `pingInterval: 6000, pingTimeout: 18000`. 

Sadly it does **not** fix the problem, I just have the `SocketProtocolError: Server ping timed out` less often. More info on this gist: https://gist.github.com/jfsimon/39e9d19ad31097d5617f

**Comment by jondubois** [comment] 2016-02-03 11:48
@jfsimon What if you set your pingInterval to 10000 (every 10 seconds)? 2 minutes is a long time but I don't think that's the problem.

Note that timeouts are normal for most applications - This can happen if the user closes their laptop suddenly, or their connection drops out, or if accessing over a mobile device and it goes to sleep.

You shouldn't be too worried if you get timeouts; it's important to log them anyway, so if you see that more connections timeout than 'normal' that could indicate something.

Are you able to reproduce the issue under controlled conditions or is this issue happening in production only? If so, I suspect it's completely normal; you might want to not log these warnings individually and instead keep track of the count over time maybe?

**Comment by jfsimon** [comment] 2016-02-03 12:06
@jondubois After some tests/logs, it appears that, on my coworker laptop (windows + chrome), when the socket is connected, it gets disconnected exactly 3 minutes after, an error is triggered: `Server ping timed out`, the socket re-connects, and so on...

Is there a way to deactivate the ping/pong? I already have events when sockets are connected and disconnected, what is this ping/pong system for? When I get `Server ping timed out` on the client side, I get `Client pong timed out` on the server side... at the same moment. I'm not sure to understand.

**Comment by jondubois** [comment] 2016-02-03 12:37
@jfsimon The ping/pong is necessary and allows the socket to know when the connection has dropped out suddenly (without sending proper close control frames). This is so that a disconnect event can be triggered in those cases. All current implementations of WS have some form of ping/pong.

I can't think of a reason why it's not working on Windows.

**Comment by jfsimon** [comment] 2016-02-03 12:56
@jondubois I know, it's really strange... I guess the problem comes from my code. I'll continue to investigate, thank you very much for your help, really appreciated! I'll keep in touch if I find something.

**Comment by jondubois** [comment] 2016-02-03 13:20
Is this user behind a corporate proxy or a firewall? Maybe there is a proxy/firewall which blocks messages sent over WebSockets. Using wss:// instead of ws:// would fix this issue; You'll have to get an SSL certificate.

**Comment by jfsimon** [comment] 2016-02-11 08:19
@jondubois OK, the problem was (of course) errors in my app. I can transfer very large objects (> 2Mo) without any problem. This project is really handy and powerful.

A very big thanks to all maintainers of SocketCluster.

**Closed** 2016-02-25 09:54 UTC

**Comment by cailosidfu** [comment] 2016-04-19 15:52
@jfsimon can you elaborate on what was wrong with your code? since I'm experiencing similar issues... :)

**Comment by vasild** [comment] 2019-07-17 09:39
Possibly related: https://github.com/SocketCluster/socketcluster/issues/506
