### ISSUE TITLE
socket client is not connected to main server

### ISSUE THREAD

**Issue by gmchaturvedi1** [SocketCluster/socketcluster#154] opened 2016-02-05 09:02 UTC
thanks for the great framework.i am facing problem to connect server from client cross orgion as mobile app and offline apps .Erros is showing Provisional  Header.

Kindly help me to way out of this.

Regards
G MChaturvedi

**Comment by jondubois** [comment] 2016-02-05 11:56
I can't reproduce this issue - Cross origin connections work fine for me on the latest version of SC. Could you give more details? What client and server versions are you using.

**Comment by jondubois** [comment] 2016-08-04 19:11
I'm closing this since this appears to  relate to a very specific use case. Feel free to reopen if you would like to pursue this issue further.

**Closed by jondubois** 2016-08-04 19:11 UTC
